# this starship.toml config is hardcoded into my matugen template for 
# starship, as toml doesn't seem to have any "include" functinality?
format = """
[╭](color9)\
[─](color9)\
[ ](color9)\
$directory(color5)\n\
[╰](color9)\
[](color9)\
[ ](color9)\
"""

palette = 'colors'

[palettes.colors]
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'
