[config]
mode        = 'dark'
# Apparently the config file can't define the wallpaper image. dayem.
# wallpaper   = '~/.config/WallPapers/WallPaper1.jpg'

[templates.hyprland]
input_path  = '~/.config/matugen/templates/Hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook   = 'hyprctl reload'

[templates.waybar]
input_path  = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook   = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path  = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook   = 'pkill -SIGUSR1 kitty'

[templates.wofi]
input_path  = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wofi/colors.css'

[templates.starship]
input_path  = '~/.config/matugen/templates/starshipColors.toml'
output_path = '~/.config/starship.toml'

[templates.blesh]
input_path  = "~/.config/matugen/templates/BleshColors"
output_path = "~/.blerc"
